WebApplication1/Controllers/CursoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Entities;
using Business.Logic;
using Microsoft.AspNetCore.Authorization;

namespace UI.Web.Controllers
{
    [Authorize(Policy = "EstadoReq")]
    public class CursoController : Controller
    {
        public IActionResult Index()
        {
            CursosLogic clog = new CursosLogic();
            ComisionLogic comlog = new ComisionLogic();
            MateriasLogic matlog = new MateriasLogic();
            var cursos = from cur in clog.getAll()
                         join coms in comlog.GetAll() on cur.IDComision equals coms.ID
                         join mats in matlog.GetAll() on cur.IDMateria equals mats.ID
                         select (cur.ID, cur.Descripcion, coms.Descripcion, mats.Descripcion, cur.AnioCalendario, cur.Cupo);
            ViewBag.cursos = cursos;
            ViewBag.comisiones = comlog.GetAll();
            ViewBag.materias = matlog.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult Nuevo(int comision1, int materia1, int añocal1, int cupo1)
        {
            try
            {
                Curso c = new Curso(0, materia1, comision1, añocal1, cupo1, "");
                CursosLogic clog = new CursosLogic();
                clog.AddNew(c);
            }
            catch(Exception ex)
            {
                TempData.Remove("msgerror");
                TempData.Add("msgerror", "No se registro el curso >>" + ex.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Modificar(int IdCurso2, int comision2, int materia2, int añocal2, int cupo2)
        {
            try
            {
                Curso c = new Curso(IdCurso2, materia2, comision2, añocal2, cupo2, "");
                CursosLogic clog = new CursosLogic();
                clog.Save(c);
            }
            catch (Exception ex)
            {
                TempData.Remove("msgerror");
                TempData.Add("msgerror", "No se guardaron los cambios >>" + ex.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(int IdCurso3)
        {
            CursosLogic clog = new CursosLogic();
            try
            {
                clog.Delete(IdCurso3);
            }
            catch (Exception ex)
            {
                TempData.Remove("msgerror");
                TempData.Add("msgerror", "No se elimino el curso >>" + ex.Message);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Inscripciones()
        {
            AlumnoInscripcionLogic al = new AlumnoInscripcionLogic();
            CursosLogic cl = new CursosLogic();
            Usuario u = Models.SessionHepler.GetUsuario(HttpContext.Session);
            List<AlumnoInscripcion> inscripciones = al.getCursosInscripto(u.IdPersona);
            List<Curso> c = cl.getAll();
            //idcur idal nota condicion
            var i = (from insc in inscripciones join cur in c on insc.IDCurso equals cur.ID select (insc, cur)).ToList();
            ViewBag.inscripciones = i;
            return View();
        }
    }
}

WebApplication1/Controllers/PlanesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Entities;
using Business.Logic;
using Microsoft.AspNetCore.Authorization;

namespace UI.Web.Controllers
{
    [Authorize(Policy = "EstadoReq")]
    public class PlanesController : Controller
    {
        public IActionResult Index()
        {
            TipoPersonas tp = Models.SessionHepler.GetTipoPersona(HttpContext.Session);
            ViewBag.tipo = tp.Descripcion;

            PlanesLogic plog = new PlanesLogic();
            EspecialidadLogic elog = new EspecialidadLogic();
            var planes = from pl in plog.GetAll()
                         join esp in elog.GetAll() on pl.IDEspecialidad equals esp.ID
                         select (pl.ID, pl.Descripcion, esp.Descripcion);
            ViewBag.planes = planes;
            ViewBag.especialidades = elog.GetAll();
            if (TempData.ContainsKey("msgerror"))
            {
                ViewBag.msgerror = TempData["msgerror"].ToString();
            }
            return View();
        }

        [HttpPost]
        public IActionResult Nuevo(string descPl1, int espec1)
        {
            Plan p = new Plan(descPl1, espec1);
            PlanesLogic plog = new PlanesLogic();
            try
            {
                plog.AddNew(p);
            }
            catch(Exception e)
            {
                TempData.Remove("msgerror");
                TempData.Add("msgerror", "No se pudo registrar el plan >>" + e.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Modificar(int Idpl2, string descPl2, int espec2)
        {
            Plan p = new Plan(Idpl2, descPl2, espec2);
            PlanesLogic plog = new PlanesLogic();
            try
            {
                plog.SaveChanges(p);
            }
            catch(Exception e)
            {
                TempData.Remove("msgerror"); 
                TempData.Add("msgerror", "No se registraron los cambios >>" + e.Message);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Eliminar(int Idpl3)
        {
            PlanesLogic plog = new PlanesLogic();
            try
            {
                plog.Delete(Idpl3);
            }
            catch(Exception e)
            {
                TempData.Remove("msgerror"); 
                TempData.Add("msgerror", "No se elimino el plan >>" + e.Message);
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/ReportController.cs
using AspNetCore.Reporting;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace UI.Web.Controllers
{
    [Authorize(Policy = "EstadoReq")]
    public class ReportController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly iPlanService planesService;
        private readonly ICursosService cursoService;
        public ReportController(IWebHostEnvironment webHostEnvironment,iPlanService planesService, ICursosService cursoService)
        {
            this.webHostEnvironment = webHostEnvironment;
            this.planesService = planesService;
            this.cursoService = cursoService;
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task <IActionResult> PrintPlanes()
        {
            string mimtype = "";
            int extension = 1;
            var path = $"{this.webHostEnvironment.WebRootPath}\\Reports\\ReportPlanes.rdlc";
            Dictionary<string, string> parameters = new Dictionary<string, string>();
           // parameters.Add("param1", "Welcome to Sarrawy Dev");
            LocalReport localReport = new LocalReport(path);
            var planes = await planesService.GetPlanes();
            localReport.AddDataSource("Planes", planes);
            var result = localReport.Execute(RenderType.Pdf, extension,parameters,mimtype); 
            return File(result.MainStream, "application/Pdf");
        }
        public async Task<IActionResult> PrintCursos()
        {
            string mimtype = "";
            int extension = 1;
            var path = $"{this.webHostEnvironment.WebRootPath}\\Reports\\ReportCursos.rdlc";
            Dictionary<string, string> parameters = new Dictionary<string, string>();
            // parameters.Add("param1", "Welcome to Sarrawy Dev");
            LocalReport localReport = new LocalReport(path);
            var cursos = await cursoService.GetCursos();
            localReport.AddDataSource("Cursos", cursos);
            var result = localReport.Execute(RenderType.Pdf, extension, parameters, mimtype);
            return File(result.MainStream, "application/Pdf");
        }
    }
}

WebApplication1/Controllers/UsuarioController.cs
using Business.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Logic;
using Microsoft.AspNetCore.Authorization;

namespace UI.Web.Controllers
{
    [Authorize(Policy = "EstadoReq")]
    public class UsuarioController : Controller
    {
        
        public IActionResult Index()
        {
            if (TempData.ContainsKey("msgerror"))
            {
                ViewBag.msgerror = TempData["msgerror"].ToString();
            }
            TipoPersonas tp = Models.SessionHepler.GetTipoPersona(HttpContext.Session);
            ViewBag.tipo = tp.Descripcion;
            if (TempData.ContainsKey("msgerror"))
            {
                ViewBag.msgerror = TempData["msgerror"].ToString();
            }
            UsuarioLogic ul = new UsuarioLogic();
            PersonaLogic pl = new PersonaLogic();
            PlanesLogic planes  =  new PlanesLogic();
            TipoPersonaLogic tpl  =  new TipoPersonaLogic();
            ViewBag.Usuarios = ul.GetAll();
            ViewBag.Personas=pl.GetAll();
            ViewBag.Tipos  =  tpl.GetAll();
            ViewBag.Planes  =  planes.GetAll();
            return View();
        }

        public IActionResult RegistrarUsuario(string email1, string nombreusuario1, string clave1,
            string nombre1, string apellido1, int idpersona1)
        {
            UsuarioLogic ul = new UsuarioLogic();
            Usuario u = new Usuario(0,  nombreusuario1,  clave1,  nombre1,  apellido1,  email1,  true,  idpersona1,  true);
            ul.AddNew(u);
            return RedirectToAction("Index");

        }

        public IActionResult RegistrarUsuario2(string email1, string nombreusuario1, string clave1,
            string nombre1, string apellido1, string telefono1, DateTime fechanacimiento1,
            string legajo1, int idpersona1, string direccion1, int plan1, int tipo1)
        {
            UsuarioLogic ul = new UsuarioLogic();
            PersonaLogic pl  =  new PersonaLogic();
            Usuario u = new Usuario(0, nombreusuario1, clave1, nombre1, apellido1, email1,  true, idpersona1, true);
            Persona p = new Persona(0, nombreusuario1, apellido1, direccion1, email1, telefono1, fechanacimiento1, Convert.ToInt32(legajo1), tipo1, plan1 );
            try
            {
                pl.AddNew(p);
                var id=pl.GetIDByMail(u.Email);
                u.IdPersona = id;
                ul.AddNew(u);
            }
            catch(Exception e)
            {
                TempData.Add("msgerror", "No se registro el nuevo usuario:" + e.Message);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int id2,string email2, string nombreusuario2, string clave2,
            string nombre2, string apellido2, string telefono2, DateTime fechanacimiento2,
            string legajo2, int idpersona2, string direccion2, int plan2, int tipo2)
        {
            UsuarioLogic ul = new UsuarioLogic();
            PersonaLogic pl = new PersonaLogic();
            Usuario u = new Usuario(id2, nombreusuario2, clave2, nombre2, apellido2, email2, true, idpersona2, true);
            Persona p = new Persona(idpersona2, nombreusuario2, apellido2, direccion2, email2, telefono2, fechanacimiento2, Convert.ToInt32(legajo2), tipo2, plan2);

            try
            {
                ul.Save(u);
                pl.SaveChange(p);
            }
            catch (Exception e)
            {
                TempData.Add("msgerror", "NO se guardaron cambios "  +  e.Message);
            }
            return RedirectToAction("Index");

        }
        public IActionResult Eliminar(int idusuario3)
        {
            UsuarioLogic ul = new UsuarioLogic();
            try
            {
                ul.Delete(idusuario3);
            }
            catch(Exception e)
            {
                TempData.Add("msgerror",  "No se elimino al usuario"  +  e.Message);
            }
            
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Academia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
        <header>

            <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top" aria-label="Second navbar example">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Academia</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    @{
                        if ((string)ViewData["Title"] != "Acceso")
                        {
                            <div class="collapse navbar-collapse" id="navbarsExample02">
                                                    <ul class="navbar-nav me-auto">
                                                        <li class="nav-item">
                                                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                                        </li>
                                                        <li class="nav-item">
                                                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                                        </li>
                                                        @switch (@ViewBag.tipo)
                                                        {
                                                            case "Administrador":
                                                                {
                                                                    <li class="nav-item">
                                                                        <div class="dropdown">
                                                                            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown">
                                                                                Administracion
                                                                            </button>
                                                                            <ul class="dropdown-menu">
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Especialidades" asp-action="Index">Especialidades</a></li>
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Comisiones" asp-action="Index">Comisiones</a></li>
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Planes" asp-action="Index">Planes</a></li>
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a></li>
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a></li>

                                                                            </ul>
                                                                        </div>
                                                                    </li>
                                                                    <li class="nav-item">
                                                                        <div class="dropdown">
                                                                            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown">
                                                                                Reportes
                                                                            </button>
                                                                            <ul class="dropdown-menu">                                                                               
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="PrintPlanes">Planes</a></li>
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Report" asp-action="PrintCursos">Cursos</a></li>

                                                                            </ul>
                                                                        </div>
                                                                    </li>

                                                                    break;
                                                                }
                                                            case "Alumno": 
                                                                { 
                                                                    <li class="=nav-item">
                                                                        <div class="dropdown">
                                                                            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown">
                                                                                Cursado
                                                                            </button>
                                                                            <ul class="dropdown-menu">
                                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Curso" asp-action="Inscripciones">Mis cursos</a></li>
                                                                            </ul>
                                                                        </div>
                                                                    </li>
                                                                    break; 
                                                                }
                                                            case "Docente": 
                                                                { 
                                                    <li class="=nav-item">
                                                        <div class="dropdown">
                                                            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown">
                                                                Notas
                                                            </button>
                                                            <ul class="dropdown-menu">
                                                                <li><a class="dropdown-item" asp-area="" asp-controller="Docentes" asp-action="CargarNotas">Cargar Notas</a></li>
                                                            </ul>
                                                        </div>
                                                    </li>
                                                                    break; 
                                                                }
                                                        }
                                                    </ul>
                                <a class="nav-link px-3" asp-area="" asp-controller="Acceso" asp-action="SessionClose">Cerrar Sesion</a>
                            </div>
                        }
                    }
                </div>
            </nav>
        
        </header>
    <br />
    <br />
    <br />
    
    <div class="container">
        @{if (!string.IsNullOrEmpty(ViewBag.msgerror))
            {
                <div class="alert alert-danger">
                    <p>@ViewBag.msgerror</p>
                </div>
            }
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>