WebApplication1/Controllers/DocentesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Entities;
using Business.Logic;

namespace UI.Web.Controllers
{
    public class DocentesController : Controller
    {
        public IActionResult CargarNotas()
        {
            ViewBag.msgerror = "";
            if (TempData.ContainsKey("msgerror"))
            {
                ViewBag.msgerror = TempData["msgerror"].ToString();
            }
            AlumnoInscripcionLogic al = new AlumnoInscripcionLogic();
            UsuarioLogic ul = new UsuarioLogic();
            int id = Models.SessionHepler.GetUsuario(HttpContext.Session).IdPersona;
            List<AlumnoInscripcion> inscripciones = al.GetInscripciones_D(id);
            //ViewBag.inscripciones = inscripciones;
            var InscAlumnos = (from i in inscripciones
                               join p in ul.GetAll()
       on i.IDAlumno equals p.ID
                               select (i, p)).ToList();
            ViewBag.inscripciones = InscAlumnos;


            
            return View();
        }

        public IActionResult Cargar(int idalumnoinscripcio, int idalumno, int idcurso, string condicion, int nota)
        {
            //
            AlumnoInscripcion ai = new AlumnoInscripcion(idalumnoinscripcio, condicion, idalumno, idcurso, nota);
            AlumnoInscripcionLogic al = new AlumnoInscripcionLogic();
            try
            {
                al.Save(ai);
            }
            catch(Exception e)
            {
                TempData.Add("msgerror","Error al cargar la nota:" + e.Message);
            }
            return RedirectToAction("CargarNotas");
        }
    }
}

WebApplication1/Views/Docentes/CargarNotas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Carga de notas";
}

<h1>Mis cursos</h1>

<table id="tabCursos" class="table table-dark table-hover">
    <th>ID Inscripcion</th>
    <th>ID Curso</th>
    <th>ID Alumno</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Condicion</th>
    <th>Nota</th>
    <th></th>

    @foreach (var ins in ViewBag.inscripciones)
    {
        <tr>
            <td>@ins.Item1.ID</td>
            <td>@ins.Item1.IDCurso</td>
            <td>@ins.Item2.IdPersona</td>
            <td>@ins.Item2.Nombre</td>
            <td>@ins.Item2.Apellido</td>
            <td>@ins.Item1.Condicion</td>
            <td>@ins.Item1.Nota</td>
            <td><button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modalcrear">Cargar Nota</button></td>
        </tr>
    }
</table>

    <div class="modal fade" id="modalcrear" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLiveLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" asp-area="" asp-controller="Docentes" asp-action="Cargar">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLiveLabel">Registrar Nota</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="form-floating">
                        <input id="idalumnoinscripcio" name="idalumnoinscripcio" type="number" class="form-control" readonly required />
                        <label for="idalumnoinscripcio">Id Inscripcion</label>
                    </div>
                    <div class="form-floating">
                        <input id="idcurso" name="idcurso" type="number" class="form-control" readonly />
                        <label for="idcurso">ID Cruso</label>
                    </div>
                    <div class="form-floating">
                        <input id="idalumno" name="idalumno" type="number" class="form-control" readonly />
                        <label for="idalumno">ID Alumno</label>
                    </div>
                    <div class="form-floating">
                        <input id="nombre" name="nombre" type="text" class="form-control" readonly />
                        <label for="nombre">Nombre</label>
                    </div>
                    <div class="form-floating">
                        <input id="apellido" name="apellido" type="text" class="form-control" readonly />
                        <label for="apellido">Apellido</label>
                    </div>
                    <label for="condicion">Condicion</label>
                    <select id="condicion" name="condicion" required>
                        <option>Inscripto</option>
                        <option>Regular</option>
                        <option>Aprobado</option>
                        <option>Desaprobado</option>
                    </select>

                    <div class="form-floating">
                        <label for="nota">Nota</label>
                        <select id="nota" name="nota" required>
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10</option>
                        </select>
                    </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

<script type="text/javascript">

    var table = document.getElementById('tabCursos'), rIndex;
    for (i = 0; i < table.rows.length; i++) {
        table.rows[i].onclick = function () {
            rIndex = this.rowsIndex;
            document.getElementById('idalumnoinscripcio').value = this.cells[0].innerHTML;
            document.getElementById('idcurso').value = this.cells[1].innerHTML;
            document.getElementById('idalumno').value = this.cells[2].innerHTML;
            document.getElementById('nombre').value = this.cells[3].innerHTML;
            document.getElementById('apellido').value = this.cells[4].innerHTML;
            for (x = 0; x < document.getElementById('condicion').options.length; x++) {
                if (this.cells[5].innerHTML == document.getElementById('condicion').options[x].innerHTML) {
                    document.getElementById('condicion').selectedIndex = x;
                    break;
                }
            }
            for (x = 0; x < document.getElementById('condicion').options.length; x++) {
                if (this.cells[6].innerHTML == document.getElementById('nota').options[x].innerHTML) {
                    document.getElementById('nota').selectedIndex = x;
                    break;
                }
            }

        };
    }

</script>